BugTracking/BugTracking/Controllers/OrganizationController.cs
using System.Web.Mvc;
using BugTracking.Business;
using BusinessObjects = BugTracking.Models;

namespace BugTracking.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrganizationController : Controller
    {

        OrganizationService orgmanager { get; } = new OrganizationService();


        // GET: Organization
        public ActionResult CreateOrganization()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrganization([Bind(Include = "Id,Name,Location,Email,TelephoneNumber, LastModified, Active")] BusinessObjects.Organization org)
        {

            var response = orgmanager.Save(org);

            if (!response.IsError)
            {
                return RedirectToAction("/OrganizationList");
            }
            else
            {
                foreach (var failer in response.ValidationResult.Errors)
                {
                    ModelState.AddModelError(failer.PropertyName, failer.ErrorMessage);
                }
                return View();
            }
        }

        public ActionResult OrganizationList()
        {
            var orglist = orgmanager.GetOrganizations();
            return View(orglist);
        }


        public ActionResult EditOrganization(long id)
        {

            var org = orgmanager.EditOrganization(id);

            if (org != null)
            {
                return View(org);
            }

            else
            {
                return RedirectToAction("/OrganizationList");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditOrganization([Bind(Include = "Id,Name,Location,Email,TelephoneNumber, LastModified, Active")] BusinessObjects.Organization org)
        {
            var response=orgmanager.SaveEdit(org);

            if (!response.IsError)
            {
                return RedirectToAction("/OrganizationList");
            }

            else
            {
                foreach (var failer in response.ValidationResult.Errors)
                {
                    ModelState.AddModelError(failer.PropertyName, failer.ErrorMessage);
                }

                return View();
            }


        }



        public ActionResult DeleteOrganization(long id)
        {
            var org = orgmanager.DeleteOrganization(id);

            if (org != null)
            {
                return View(org);
            }

            else
            {
                return RedirectToAction("/OrganizationList");
            }
        }


        [HttpPost, ActionName("DeleteOrganization")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
           
            var response = orgmanager.DeleteConfirmed(id);
            

            if (!response.IsError)
            {
                return RedirectToAction("/OrganizationList");
            }

            else

            {
             

                foreach (var failer in response.ValidationResult.Errors)
                {
                    ModelState.AddModelError(failer.PropertyName, failer.ErrorMessage);
                }
                var org = orgmanager.DeleteOrganization(id);
                return View(org);
            }
        }
    }
}

BugTracking/BugTracking/Views/Organization/CreateOrganization.cshtml
@model BugTracking.Models.Organization




<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Create New Organization </h5>
            </div>
            <div class="ibox-content">

                @using (Html.BeginForm("CreateOrganization", "Organization", FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary("", new { @class = "text-danger" })


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Name, "Name", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name" } })

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Location, "Location", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Location" } })</div>
                            </div>
                        </div>
                    </div>



                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.TelephoneNumber, "Telephone number", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.TelephoneNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Telephone" } })</div>
                            </div>
                        </div>
                    </div>



                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Email, "Email", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email" } })</div>
                            </div>
                        </div>
                    </div>





                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <a class="btn btn-secondary" href="/Organization/OrganizationList" role="button">Cancel</a>
                            <button class="btn btn-primary" type="submit">Add Organization</button>
                        </div>
                    </div>
                }




            </div>
        </div>
    </div>
</div>

BugTracking/BugTracking/Views/Organization/DeleteOrganization.cshtml
@model BugTracking.Models.Organization



<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Delete Organization </h5>
            </div>
            <div class="ibox-content">

                @using (Html.BeginForm("DeleteOrganization", "Organization", FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary("", new { @class = "text-danger" })

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Name, "Organization Name", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.TextBoxFor(model => model.Name, new { @class = "form-control", @readonly = true })</div>
                            </div>
                        </div>
                    </div>


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Location, "Location", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.TextBoxFor(model => model.Location, new { @class = "form-control", @readonly = true })</div>
                            </div>
                        </div>
                    </div>


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.TelephoneNumber, "Telephone Number", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.TextBoxFor(model => model.TelephoneNumber, new { @class = "form-control", @readonly = true })</div>
                            </div>
                        </div>
                    </div>



                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Email, "Email", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.TextBoxFor(model => model.Email, new { @class = "form-control", @readonly = true })</div>
                            </div>
                        </div>
                    </div>






                    <div class="hr-line-dashed"></div>

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">

                            <a class="btn btn-secondary" href="/Organization/OrganizationList" role="button">Cancel</a>
                            <button class="btn btn-primary" type="submit">Delete Organization</button>

                        </div>
                    </div>
                }




            </div>
        </div>
    </div>
</div>

BugTracking/BugTracking/Views/Organization/EditOrganization.cshtml
@model BugTracking.Models.Organization


<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Edit Organization </h5>
            </div>
            <div class="ibox-content">

                @using (Html.BeginForm("EditOrganization", "Organization", FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.Active)

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Name, "Organization Name", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })</div>
                            </div>
                        </div>
                    </div>


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Location, "Location", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })</div>
                            </div>
                        </div>
                    </div>


                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.TelephoneNumber, "Telephone Number", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.TelephoneNumber, new { htmlAttributes = new { @class = "form-control" } })</div>
                            </div>
                        </div>
                    </div>



                    <div class="hr-line-dashed"></div>
                    <div class="form-group">


                        @Html.LabelFor(model => model.Email, "Email", new { @class = "col-sm-2 control-label" })

                        <div class="col-sm-10">
                            <div class="row">
                                <div class="col-md-3">@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })</div>
                            </div>
                        </div>
                    </div>





                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <a class="btn btn-secondary" href="/Organization/OrganizationList" role="button">Cancel</a>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </div>
                }




            </div>
        </div>
    </div>
</div>

BugTracking/BugTracking/Views/Organization/OrganizationList.cshtml
@model IEnumerable<BugTracking.Models.Organization>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>Organizations</h2>
    </div>
</div>


<div class="row">

    <div class="col-lg-12">

        <div class="ibox float-e-margins">

            <div class="ibox-content">


                <a class="btn btn-primary" href=@Url.Action("CreateOrganization", "Organization") role="button">New</a>


                <table class="table table-hover">
                    <thead>
                        <tr>


                            <th>@Html.DisplayNameFor(model => model.Name)</th>
                            <th>@Html.DisplayNameFor(model => model.Location)</th>
                            <th>@Html.DisplayNameFor(model => model.TelephoneNumber)</th>
                            <th>@Html.DisplayNameFor(model => model.Email)</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>


                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Location)</td>
                                <td>@Html.DisplayFor(modelItem => item.TelephoneNumber, "Telephone Number")</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>

                                <td class="text-navy">
                                    <a href=@Url.Action("EditOrganization", "Organization", new {id=item.ID})><i class="fa fa-cog"></i></a>
                                    <a href=@Url.Action("DeleteOrganization", "Organization", new {id=item.ID})><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>